import { WorldRecord } from "./types";

export const INITIAL_RECORDS: WorldRecord[] = [
  {
    id: "rec_1",
    title: "Largest Collection of Video Games",
    description: "Antonio Romero Monteiro (USA) has amassed 24,268 video games, filling an entire custom-built room in Texas.",
    category: "Gaming",
    holder: "Antonio Romero Monteiro",
    dateSet: "2024-03-12",
    location: "Richmond, Texas, USA",
    imageUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=800",
    likesCount: 1240,
    commentsCount: 89,
    tags: ["gaming", "collection", "rare"],
    isVerified: true,
    timestamp: Date.now() - 1000 * 60 * 60 * 24 * 2
  },
  {
    id: "rec_2",
    title: "Fastest Human to Solve 3x3x3 Cube",
    description: "Max Park (USA) set the definitive world record with a staggering time of 3.13 seconds at the Pride in Long Beach 2023 event.",
    category: "Skill",
    holder: "Max Park",
    dateSet: "2023-06-11",
    location: "Long Beach, California, USA",
    imageUrl: "https://images.unsplash.com/photo-1591991731833-b4807cf7ef94?auto=format&fit=crop&q=80&w=800",
    likesCount: 5600,
    commentsCount: 432,
    tags: ["cubing", "speed", "logic"],
    isVerified: true,
    timestamp: Date.now() - 1000 * 60 * 60 * 12
  },
  {
    id: "rec_gaming_mc",
    title: "Minecraft Speedrun (Any% Glitchless)",
    description: "Brenton achieved a mind-blowing time of 7 minutes and 1 second in the 1.16+ Any% RSG category, showcasing perfect RNG and movement.",
    category: "Gaming",
    holder: "Brenton",
    dateSet: "2023-11-20",
    location: "Online",
    imageUrl: "https://images.unsplash.com/photo-1627398242454-45a1465c2479?auto=format&fit=crop&q=80&w=800",
    likesCount: 8420,
    commentsCount: 215,
    tags: ["minecraft", "speedrun", "rsg"],
    isVerified: true,
    timestamp: Date.now() - 10000000
  },
  {
    id: "rec_gaming_hk",
    title: "Hollow Knight Speedrun (Any%)",
    description: "fireb0rn set a legendary pace in the Any% category with a time of 32 minutes and 17 seconds, utilizing high-level movement glitches and skips.",
    category: "Gaming",
    holder: "fireb0rn",
    dateSet: "2023-05-15",
    location: "Online",
    imageUrl: "https://images.unsplash.com/photo-1614680376593-902f74cf0d41?auto=format&fit=crop&q=80&w=800",
    likesCount: 4312,
    commentsCount: 156,
    tags: ["hollow-knight", "any%", "glitched"],
    isVerified: true,
    timestamp: Date.now() - 20000000
  },
  {
    id: "rec_gaming_er",
    title: "Elden Ring Speedrun (Any%)",
    description: "Distortion2 broke the internet by becoming the first person to beat the massive RPG in under 7 minutes using advanced zip glitches.",
    category: "Gaming",
    holder: "Distortion2",
    dateSet: "2022-04-12",
    location: "Online",
    imageUrl: "https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?auto=format&fit=crop&q=80&w=800",
    likesCount: 15200,
    commentsCount: 890,
    tags: ["elden-ring", "unrestricted", "zip"],
    isVerified: true,
    timestamp: Date.now() - 30000000
  },
  {
    id: "rec_3",
    title: "Tallest Living Woman",
    description: "Rumeysa Gelgi (Turkey) stands at 215.16 cm (7 ft 0.7 in) and uses her platform to advocate for people with visible differences.",
    category: "Body",
    holder: "Rumeysa Gelgi",
    dateSet: "2024-05-20",
    location: "Istanbul, Turkey",
    imageUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=800",
    likesCount: 890,
    commentsCount: 45,
    tags: ["human", "extraordinary", "turkey"],
    isVerified: true,
    timestamp: Date.now() - 1000 * 60 * 60 * 48
  },
  {
    id: "rec_sport_1",
    title: "Fastest 100m Sprint",
    description: "Usain Bolt (Jamaica) set the world record at the 2009 World Championships in Berlin, clocking an incredible 9.58 seconds.",
    category: "Sport",
    holder: "Usain Bolt",
    dateSet: "2009-08-16",
    location: "Berlin, Germany",
    imageUrl: "https://images.unsplash.com/photo-1599586120429-48281b6f0ece?auto=format&fit=crop&q=80&w=800",
    likesCount: 25400,
    commentsCount: 1200,
    tags: ["athletics", "sprint", "legend"],
    isVerified: true,
    timestamp: Date.now() - 50000000
  },
  {
    id: "rec_sport_2",
    title: "Fastest Marathon",
    description: "Eliud Kipchoge (Kenya) broke his own world record at the Berlin Marathon, finishing in 2:01:09.",
    category: "Sport",
    holder: "Eliud Kipchoge",
    dateSet: "2022-09-25",
    location: "Berlin, Germany",
    imageUrl: "https://images.unsplash.com/photo-1530915534664-4ac6423816b7?auto=format&fit=crop&q=80&w=800",
    likesCount: 12300,
    commentsCount: 450,
    tags: ["marathon", "running", "endurance"],
    isVerified: true,
    timestamp: Date.now() - 40000000
  },
  {
    id: "rec_body_1",
    title: "Tallest Living Man",
    description: "Sultan Kösen (Turkey) is the tallest living man at 251 cm (8 ft 2.8 in), a height caused by pituitary gigantism.",
    category: "Body",
    holder: "Sultan Kösen",
    dateSet: "2009-02-08",
    location: "Ankara, Turkey",
    imageUrl: "https://images.unsplash.com/photo-1531384441138-2736e62e0919?auto=format&fit=crop&q=80&w=800",
    likesCount: 3400,
    commentsCount: 180,
    tags: ["height", "gigantism", "human"],
    isVerified: true,
    timestamp: Date.now() - 60000000
  },
  {
    id: "rec_body_2",
    title: "Tallest Man Ever",
    description: "Robert Wadlow (USA) reached a record height of 272 cm (8 ft 11.1 in) before his death in 1940.",
    category: "Body",
    holder: "Robert Wadlow",
    dateSet: "1940-06-27",
    location: "Alton, Illinois, USA",
    imageUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=800",
    likesCount: 56000,
    commentsCount: 2300,
    tags: ["history", "height", "legend"],
    isVerified: true,
    timestamp: Date.now() - 70000000
  },
  {
    id: "rec_gaming_sm64",
    title: "Super Mario 64 (120 Stars)",
    description: "weegee set the benchmark for high-level Mario 64 speedrunning with a 1:37:35 time in the 120-star category.",
    category: "Gaming",
    holder: "weegee",
    dateSet: "2023-05-04",
    location: "Online",
    imageUrl: "https://images.unsplash.com/photo-1550745672-03460458dc87?auto=format&fit=crop&q=80&w=800",
    likesCount: 9200,
    commentsCount: 310,
    tags: ["nintendo", "speedrun", "mario"],
    isVerified: true,
    timestamp: Date.now() - 15000000
  },
  {
    id: "troll_5",
    title: "Most Browser Tabs Open (Without Purpose)",
    description: "Successfully maintained 412 open tabs across 6 windows, 80% of which were 'to be read' articles from 2018.",
    category: "Troll",
    holder: "T. Ab-Collector",
    dateSet: "2025-04-30",
    location: "Desk Chair",
    imageUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=800",
    likesCount: 15600,
    commentsCount: 890,
    tags: ["funny", "tech", "chaos"],
    isVerified: true,
    timestamp: Date.now()
  },
  {
    id: "troll_6",
    title: "Fastest Sock Disappearance",
    description: "A pair of matching socks entered the laundry machine at 2:00 PM; by 2:45 PM, only one remained, setting a record for inter-dimensional travel.",
    category: "Troll",
    holder: "L. Aundry",
    dateSet: "2025-04-15",
    location: "Washing Machine",
    imageUrl: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&q=80&w=800",
    likesCount: 42000,
    commentsCount: 120,
    tags: ["funny", "quantum-socks", "laundry"],
    isVerified: true,
    timestamp: Date.now() - 200
  },
  {
    id: "troll_1",
    title: "Most Efficient Procrastinator",
    description: "Successfully delayed reading this description for exactly 4 minutes while thinking about what to have for lunch.",
    category: "Troll",
    holder: "A. Slacker",
    dateSet: "2025-01-01",
    location: "Everywhere",
    imageUrl: "https://images.unsplash.com/photo-1541199160986-224eb0134568?auto=format&fit=crop&q=80&w=800",
    likesCount: 9999,
    commentsCount: 0,
    tags: ["funny", "relatable", "procrastination"],
    isVerified: true,
    timestamp: Date.now()
  },
  {
    id: "troll_4",
    title: "World's Longest 'Wait, what was I doing?' Moment",
    description: "Stared into an open refrigerator for 27 consecutive minutes before realizing they actually needed a towel from the laundry room.",
    category: "Troll",
    holder: "Forgetful Frank",
    dateSet: "2025-03-12",
    location: "The Kitchen",
    imageUrl: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&q=80&w=800",
    likesCount: 777,
    commentsCount: 3,
    tags: ["brain-fog", "funny", "kitchen"],
    isVerified: false,
    timestamp: Date.now() - 100
  }
];
